### ISSUE TITLE
Height Bug

### ISSUE THREAD

**Issue by Zachattack525** [LibreVR/RoboRevive#22] opened 2017-04-12 17:13 UTC
I was told that using RoboRevive would fix the 360 height bug. It didn't. any reason why?

**Comment by CarrotSurvivor** [comment] 2017-04-12 17:23
You need to launch the game using the desktop shortcut, do not launch using revive.

**Comment by Zachattack525** [comment] 2017-04-13 15:35
i did launch it with the desktop shortcut. no fix

**Comment by CarrotSurvivor** [comment] 2017-04-13 15:51
Did you try again? If not working still just use advanced settings floor fix, but hold your controller above your head to offset the height.

**Comment by Zachattack525** [comment] 2017-04-13 16:05
clever idea. ill try it

**Comment by Zachattack525** [comment] 2017-04-13 17:55
it worked! but hopefully you'll be able to find out what actually causes the problem

**Comment by Armada651** [comment] 2017-04-13 17:56
I still think you're playing through Revive, in any case the bug will be fixed in the next release of Revive.

**Comment by Zachattack525** [comment] 2017-04-15 13:23
nice! also, a little thing i noticed: when you use the floor fix above your head, then go through a loading screen, it shoves you through the floor, and you need to fix it again at the actual floor, then fix it again after the next loading screen where you'll be shoved through the ceiling. essentially, it cant decide whether it wants to do the height bug or not.

**Comment by Armada651** [comment] 2017-04-15 13:28
@Zachattack525 The height bug in Revive is due to the Robo Recall expecting the calibrated height to always be zeroed out. And the fact that you're encountering the bug is a clear indication that you are in fact starting RoboRecall through Revive.

You probably tried patching Robo Recall once. You should go to `C:\Program Files\Oculus\Software\Software\epic-games-odin\RoboRecall\Binaries\Win64` and look for any DLLs named `xinput1_3.dll` or `xinput9_1_0.dll` and delete those.

**Comment by Zachattack525** [comment] 2017-04-15 13:33
alrighty, i deleted them, lets see if it works

**Comment by Armada651** [comment] 2017-04-15 13:34
Remember to use the desktop shortcut.

**Comment by Zachattack525** [comment] 2017-04-15 13:34
ok, i know

**Comment by Zachattack525** [comment] 2017-04-15 13:42
ummm... little issue... just yesterday, i had to reset my PC due to some issues, and im trying to reinstall roborevive, but it keeps saying it cant find my game directory. ive reinstalled robo recall, but it still cant find it

**Comment by Armada651** [comment] 2017-04-15 13:43
What is the exact error?

**Comment by Zachattack525** [comment] 2017-04-15 13:44
Oculus software not found. Go to oculus.com/setup to install it.

**Comment by Armada651** [comment] 2017-04-15 13:46
Does this happen immediately after starting the installer or when you actually press Install?

**Comment by Zachattack525** [comment] 2017-04-15 13:46
immediately

**Comment by Armada651** [comment] 2017-04-15 13:49
That's strange, maybe they moved a registry key? Can you go to regedit and look if `HKEY_CURRENT_USER\Software\Oculus VR, LLC\Oculus\Libraries` exists?

**Comment by Zachattack525** [comment] 2017-04-15 13:53
it does

**Comment by Armada651** [comment] 2017-04-15 13:56
Very odd, well you'll have to do it manually then. You can download the files without the installer here: https://github.com/LibreVR/RoboRevive/releases/download/v1.0/RoboRevive-NoInstaller.zip

Extract it in your Robo Recall directory (merging the two Engine folders) and then run Revive.robo to install the mod.

**Comment by Zachattack525** [comment] 2017-04-15 13:57
alright

**Comment by Zachattack525** [comment] 2017-04-15 13:57
done

**Comment by Zachattack525** [comment] 2017-04-15 13:58
but then how do i launch the game without the shortcut?

**Comment by Armada651** [comment] 2017-04-15 14:01
Make your own shortcut, the executable is: `RoboRecall\Binaries\Win64\RoboRecall-Win64-Shipping.exe`

**Comment by Zachattack525** [comment] 2017-04-15 14:02
ok

**Comment by Zachattack525** [comment] 2017-04-15 14:05
and now it keeps saying i dont own the game...
it keeps tellinfg me "entitlement not found"

**Comment by Armada651** [comment] 2017-04-15 14:06
Yeah that's also normally fixed by the installer. Go to the Oculus Software > Settings > Beta > Restart Oculus.

**Comment by Zachattack525** [comment] 2017-04-15 14:07
done. testing now

**Comment by Zachattack525** [comment] 2017-04-15 14:09
same issue

**Comment by Armada651** [comment] 2017-04-15 14:10
And there are no xinput DLLs in the `RoboRecall\Binaries\Win64\` directory?

**Comment by Zachattack525** [comment] 2017-04-15 14:12
none

**Comment by Armada651** [comment] 2017-04-15 14:13
In RoboRecall try opening the pause menu (use the menu button on the Vive controller) and go to Settings > Tracking and enable 360 tracking.

**Comment by Zachattack525** [comment] 2017-04-15 14:14
i cant open roborecall, it tells me i dont have the entitlement

**Comment by Armada651** [comment] 2017-04-15 14:15
Oh sorry I thought you meant you still had the Heigh Issue. In that case reboot your PC.

**Comment by Zachattack525** [comment] 2017-04-15 14:18
ok

**Comment by Zachattack525** [comment] 2017-04-15 14:26
entitlement not found...

**Comment by Zachattack525** [comment] 2017-04-15 14:28
why, robo recall, why do you do this to me?

**Comment by Armada651** [comment] 2017-04-15 14:29
You did actually buy the game right? It sounds like the Oculus software wasn't installed correctly. Try reinstalling the Oculus software.

**Comment by Zachattack525** [comment] 2017-04-15 14:30
yes, i did actually buy the game

**Comment by Zachattack525** [comment] 2017-04-15 14:31
interestingly, when i uninstalled the oculus app, none of my directories were deleted. should i delete them?

**Comment by Zachattack525** [comment] 2017-04-15 14:34
yes or no?

**Comment by Armada651** [comment] 2017-04-15 14:36
I can't really give advice on how you should reinstall the Oculus software.

**Comment by Zachattack525** [comment] 2017-04-15 14:36
fair enough

**Comment by Zachattack525** [comment] 2017-04-15 14:38
just asking for a recommendation

**Comment by Zachattack525** [comment] 2017-04-15 14:41
i decided to uninstall robo recall, because when i tried to reinstall oculus earlier and just now, they both needed robo recall to finish installing something, and none of the other games i had did

**Comment by Zachattack525** [comment] 2017-04-15 14:42
im reinstalling it now

**Comment by Zachattack525** [comment] 2017-04-15 14:42
that issue mightve also caused the installer to not work

**Comment by Zachattack525** [comment] 2017-04-15 14:52
im reinstalling oculus from the ground up. deleted the leftover folders

**Comment by Zachattack525** [comment] 2017-04-15 15:25
fixed

**Comment by Zachattack525** [comment] 2017-04-15 15:26
i uninstalled oculus, deleted all the files left over, reinstalled oculus, reinstalled robo recall, installed robo revive (installer still didnt work, though) and it worked!

**Comment by Armada651** [comment] 2017-04-15 15:49
Okay, so that confirms that height issues were not caused by RoboRevive.

**Closed by Armada651** 2017-04-15 15:49 UTC
